version: 1
disable_existing_loggers: False

formatters:
    basic:
        format: '[{asctime}] [{levelname:<8}] {name}: {message}'
        datefmt: '%Y-%m-%d %H:%M:%S'
        style: '{'

handlers:
    file:
        class: logging.handlers.TimedRotatingFileHandler
        formatter: basic
        filename: logs/logger.log
        encoding: utf-8
        when: W0
        interval: 1
        backupCount: 4

    console:
        class: logging.StreamHandler
        formatter: basic
        stream: ext://sys.stdout

loggers:
    discord:
        level: INFO
        handlers: [file, console]
        propagate: false

    bot.main:
        level: DEBUG
        handlers: [file, console]
        propagate: false
